version: '3.8'

services:
    app:
        container_name: backend_full_laravel
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./backend_full_laravel:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www
        depends_on:
            - db

    db:
        image: postgres
        container_name: postgres
        volumes:
            - /var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: blog
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password

    mongo:
        image: mongo:7
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8081:80"
        volumes:
            - ./src:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db

    react:
        container_name: react_app
        build:
            context: ./frontend_react
            dockerfile: Dockerfile
        volumes:
            - ./frontend_react:/app
        ports:
            - "3000:3000"
        working_dir: /app
        environment:
            - CHOKIDAR_USEPOLLING=true

    minio:
        image: minio/minio
        container_name: minio
        ports:
            - "9001:9000" # MinIO API
            - "9002:9001" # MinIO Console (UI)
        volumes:
            - minio-data:/data
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: password123
        command: server /data --console-address ":9001"


volumes:
    minio-data: